#!/bin/bash
#PBS -P fr3 
#PBS -q normal
#PBS -l walltime=00:25:00
#PBS -l mem=55000MB
#PBS -l ncpus=16
#PBS -l wd
module load python/2.7.3
module load python/2.7.3-matplotlib
python chapter7.py $PBS_ARRAY_INDEX 1

