#!/bin/bash

for i in {338..338}; do
    #qsub -v PBS_ARRAY_INDEX=$i ch7jobs_init
    qsub -v PBS_ARRAY_INDEX=$i ch7jobsCS
    qsub -v PBS_ARRAY_INDEX=$i ch7jobsSWA
    qsub -v PBS_ARRAY_INDEX=$i ch7jobsOA
    qsub -v PBS_ARRAY_INDEX=$i ch7jobsCSHL
done

