#!/bin/bash

qsub -v PBS_ARRAY_INDEX=0 -v PBS_SCEN=CS ch7jobs
#qsub -v PBS_ARRAY_INDEX=0 -v PBS_SCEN=SWA ch7jobs
#qsub -v PBS_ARRAY_INDEX=0 -v PBS_SCEN=OA ch7jobs
#qsub -v PBS_ARRAY_INDEX=0 -v PBS_SCEN=NS ch7jobs

#for i in {0..110}; do
#    qsub -v PBS_ARRAY_INDEX=$i ch7jobs
#done
